/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5tz2ZmHp5z9cRBR3D1tqVc
import { createUseStyleTokens } from "@plasmicapp/react-web";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 5tz2ZmHp5z9cRBR3D1tqVc/projectModule
import projectcss from "./plasmic.module.css"; // plasmic-import: 5tz2ZmHp5z9cRBR3D1tqVc/projectcss

const data = {
  base: `${projectcss.plasmic_tokens}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
