/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5tz2ZmHp5z9cRBR3D1tqVc
// Component: VIIlU2j3CzWY
import * as React from "react";
import { ClientHomepage } from "../../../app/page-client"; // plasmic-import: VIIlU2j3CzWY/rscClient

const $$ = {};
import {
  executeServerQuery,
  mkPlasmicUndefinedServerProxy,
  makeQueryCacheKey
} from "@plasmicapp/react-web/lib/data-sources";

export async function executeServerQueries($ctx) {
  const serverQueries = {};
  const queryVarToKey = {};
  const $queries = {};
  for (const key of Object.keys(serverQueries)) {
    const sq = serverQueries[key];
    const params = sq.execParams();
    const cacheKey = makeQueryCacheKey(sq.id, params);
    queryVarToKey[key] = cacheKey;
    $queries[cacheKey] = mkPlasmicUndefinedServerProxy();
  }
  do {
    await Promise.all(
      Object.keys(serverQueries).map(async key => {
        const cacheKey = queryVarToKey[key];
        $queries[cacheKey] = (
          await executeServerQuery(serverQueries[key])
        ).data;
        if (!$queries[cacheKey]?.isUndefinedServerProxy) {
          delete serverQueries[key];
        }
      })
    );
  } while (
    Object.values($queries).some(value => value?.isUndefinedServerProxy)
  );

  return $queries;
}

function mkPathFromRouteAndParams(route, params) {
  if (!params) {
    return route;
  }
  let path = route;
  for (const [key, value] of Object.entries(params)) {
    if (typeof value === "string") {
      path = path.replace(`[${key}]`, value);
    } else if (Array.isArray(value)) {
      if (path.includes(`[[...${key}]]`)) {
        path = path.replace(`[[...${key}]]`, value.join("/"));
      } else if (path.includes(`[...${key}]`)) {
        path = path.replace(`[...${key}]`, value.join("/"));
      }
    }
  }
  return path;
}

export async function PlasmicHomepageServer(props) {
  const { params, searchParams, ...rest } = props;
  const pageRoute = "/";
  const pageParams = (await params) ?? {};
  const pagePath = mkPathFromRouteAndParams(pageRoute, pageParams);
  const $ctx = {
    pageRoute,
    pagePath,
    params: pageParams,
    query: searchParams
  };
  const $serverQueries = await executeServerQueries($ctx);
  return <ClientHomepage {...rest} $serverQueries={$serverQueries} />;
}
